<a href="https://colab.research.google.com/github/Hubert1234567890/python_data_science-/blob/main/pandas/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
country=['india','srilanka','china','usa','brazil'] #square braces
pd.Series(country)

0       india
1    srilanka
2       china
3         usa
4      brazil
dtype: object

In [ ]:
scores =[30,89,56,45]
pd.Series(scores)

0    30
1    89
2    56
3    45
dtype: int64

In [ ]:
## custom indexing
subject=['maths','english','hindi','science']
marks=[56,78,97,67]
pd.Series(marks,index = subject,name = 'shivam  marks') ## we just use a keyword index

maths      56
english    78
hindi      97
science    67
Name: shivam ke marks, dtype: int64

In [ ]:
## series from dictionary
marks={
    'maths' :98,
    'science':89,
    'english': 93
}
shivam_marks =pd.Series(marks,name='shivam ke marks')
shivam_marks

maths      98
science    89
english    93
Name: shivam ke marks, dtype: int64

attributes of Series

In [ ]:
## size
shivam_marks.size

3

In [ ]:
## dtype
shivam_marks.dtype

dtype('int64')

In [ ]:
## name attribute (name of a series is its attribute )
shivam_marks.name

'shivam ke marks'

In [ ]:
## is_unique
shivam_marks.is_unique

True

In [ ]:
## index
print(shivam_marks.index)
## values
print(shivam_marks.values)

Index(['maths', 'science', 'english'], dtype='object')
[98 89 93]

In [4]:
##reading csv files
import pandas as pd
import numpy as np
subs = pd.read_csv('/content/subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [7]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col= 'match_no')#index_col indicates which
##column will be used as the index

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [20]:
movies= pd.read_csv('/content/bollywood.csv')
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [21]:
movies.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [22]:
movies.tail()

                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar

In [24]:
movies.sample(5)

                                movie                   lead
1099         Loins of Punjab Presents           Shabana Azmi
704   Shirin Farhad Ki Toh Nikal Padi           Freny Bhagat
1437                        Gangaajal             Ajay Devgn
303                        Rough Book  Tannishtha Chatterjee
574                       Akaash Vani          Kartik Aaryan

In [29]:
movie_series= movies["movie"]
movie_series

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1495                  Hum Tumhare Hain Sanam
1496                     Aankhen (2002 film)
1497                         Saathiya (film)
1498                          Company (film)
1499                    Awara Paagal Deewana
Name: movie, Length: 1500, dtype: object

In [31]:
lead_series=movies["lead"]
lead_series

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [34]:
lead_series.value_counts()# its value_counts not value count

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64